Computing dependencies
Analyzing 138 sources with 0 local dependencies
ninja: Entering directory `output/soimort__you-get'
[1/154] check you_get.cli_wrapper.player.mplayer
[2/154] check you_get.cli_wrapper.openssl.__init__
[3/154] check you_get.cli_wrapper.downloader.__init__
[4/154] check you_get.cli_wrapper.player.__main__
[5/154] check you_get.cli_wrapper.transcoder.__init__
[6/154] check you_get.cli_wrapper.transcoder.ffmpeg
[7/154] check you_get.util.__init__
[8/154] check you_get.cli_wrapper.player.dragonplayer
[9/154] check you_get.cli_wrapper.transcoder.libav
[10/154] check you_get.version
[11/154] check tests.__init__
[12/154] check you_get.cli_wrapper.__init__
[13/154] check you_get.cli_wrapper.transcoder.mencoder
[14/154] check you_get.cli_wrapper.player.gnome_mplayer
[15/154] check you_get.cli_wrapper.player.vlc
[16/154] check you_get.cli_wrapper.player.wmp
[17/154] check you_get.util.os
[18/154] check you_get.processor.rtmpdump
[19/154] check you_get.json_output
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/soimort__you-get/pyi/you_get/json_output.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/soimort__you-get/imports/you_get.json_output.imports --module-name you_get.json_output -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/soimort__you-get/pyi/you_get/json_output.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/json_output.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/json_output.py", line 15, in output: No attribute 'dash_streams' on VideoExtractor [attribute-error]
  In Union[Any, VideoExtractor]
Called from (traceback):
  line 66, in download_urls
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/json_output.py", line 16, in output: No attribute 'dash_streams' on VideoExtractor [attribute-error]
  In Union[Any, VideoExtractor]
Called from (traceback):
  line 66, in download_urls
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/json_output.py", line 20, in output: No attribute 'audiolang' on VideoExtractor [attribute-error]
  In Union[Any, VideoExtractor]
Called from (traceback):
  line 66, in download_urls
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/json_output.py", line 21, in output: No attribute 'audiolang' on VideoExtractor [attribute-error]
  In Union[Any, VideoExtractor]
Called from (traceback):
  line 66, in download_urls
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/json_output.py", line 26, in output: No attribute 'referer' on VideoExtractor [attribute-error]
  In Union[Any, VideoExtractor]
Called from (traceback):
  line 66, in download_urls
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/json_output.py", line 28, in output: No attribute 'ua' on VideoExtractor [attribute-error]
  In Union[Any, VideoExtractor]
Called from (traceback):
  line 66, in download_urls

For more details, see https://google.github.io/pytype/errors.html#attribute-error
[20/154] check you_get.cli_wrapper.player.__init__
[21/154] check you_get.processor.join_ts
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/soimort__you-get/pyi/you_get/processor/join_ts.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/soimort__you-get/imports/you_get.processor.join_ts.imports --module-name you_get.processor.join_ts -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/soimort__you-get/pyi/you_get/processor/join_ts.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/processor/join_ts.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/processor/join_ts.py", line 16, in guess_output: unsupported operand type(s) for item retrieval: 'Iterator[nothing]' and 'int' [unsupported-operands]
  No attribute '__getitem__' on Iterator[nothing]
Called from (traceback):
  line 65, in current file
  line 62, in main
  line 23, in concat_ts
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/processor/join_ts.py", line 16, in guess_output: unsupported operand type(s) for item retrieval: 'Iterator' and 'int' [unsupported-operands]
  No attribute '__getitem__' on Iterator

For more details, see https://google.github.io/pytype/errors.html#unsupported-operands
[22/154] check you_get.util.term
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/soimort__you-get/pyi/you_get/util/term.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/soimort__you-get/imports/you_get.util.term.imports --module-name you_get.util.term -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/soimort__you-get/pyi/you_get/util/term.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/util/term.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/util/term.py", line 7, in get_terminal_size: Function fcntl.ioctl was called with the wrong arguments [wrong-arg-types]
         Expected: (__fd, __request, __arg: int = ..., ...)
  Actually passed: (__fd, __request, __arg: str)

For more details, see https://google.github.io/pytype/errors.html#wrong-arg-types
[23/154] check setup
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/soimort__you-get/pyi/setup.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/soimort__you-get/imports/setup.imports --module-name setup -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/soimort__you-get/pyi/setup.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/setup.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/setup.py", line 16, in <module>: No attribute '__version__' on module [attribute-error]

For more details, see https://google.github.io/pytype/errors.html#attribute-error
[24/154] check you_get.processor.join_flv
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/soimort__you-get/pyi/you_get/processor/join_flv.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/soimort__you-get/imports/you_get.processor.join_flv.imports --module-name you_get.processor.join_flv -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/soimort__you-get/pyi/you_get/processor/join_flv.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/processor/join_flv.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/processor/join_flv.py", line 292, in guess_output: unsupported operand type(s) for item retrieval: 'Iterator[nothing]' and 'int' [unsupported-operands]
  No attribute '__getitem__' on Iterator[nothing]
Called from (traceback):
  line 365, in current file
  line 362, in main
  line 299, in concat_flv
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/processor/join_flv.py", line 292, in guess_output: unsupported operand type(s) for item retrieval: 'Iterator' and 'int' [unsupported-operands]
  No attribute '__getitem__' on Iterator

For more details, see https://google.github.io/pytype/errors.html#unsupported-operands
[25/154] check you_get.util.git
[26/154] check you_get.util.log
[27/154] check you_get.util.fs
[28/154] check you_get.processor.join_mp4
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/soimort__you-get/pyi/you_get/processor/join_mp4.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/soimort__you-get/imports/you_get.processor.join_mp4.imports --module-name you_get.processor.join_mp4 -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/soimort__you-get/pyi/you_get/processor/join_mp4.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/processor/join_mp4.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/processor/join_mp4.py", line 346, in read_avc1: No attribute 'type' on None [attribute-error]
  In Optional[Any]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/processor/join_mp4.py", line 347, in read_avc1: No attribute 'size' on None [attribute-error]
  In Optional[Any]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/processor/join_mp4.py", line 577, in read_mp4a: No attribute 'type' on None [attribute-error]
  In Optional[Any]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/processor/join_mp4.py", line 578, in read_mp4a: No attribute 'size' on None [attribute-error]
  In Optional[Any]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/processor/join_mp4.py", line 902, in guess_output: unsupported operand type(s) for item retrieval: 'Iterator[nothing]' and 'int' [unsupported-operands]
  No attribute '__getitem__' on Iterator[nothing]
Called from (traceback):
  line 945, in current file
  line 942, in main
  line 909, in concat_mp4
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/soimort__you-get/src/you_get/processor/join_mp4.py", line 902, in guess_output: unsupported operand type(s) for item retrieval: 'Iterator' and 'int' [unsupported-operands]
  No attribute '__getitem__' on Iterator

For more details, see https://google.github.io/pytype/errors.html
ninja: build stopped: subcommand failed.
Leaving directory 'output/soimort__you-get'
