Computing dependencies
Analyzing 260 sources with 0 local dependencies
ninja: Entering directory `output/donnemartin__interactive-coding-challenges'
[1/260] check sum_two.__init__
[2/260] check generate_primes.__init__
[3/260] check donnemartin__interactive-coding-challenges.graphs_trees.invert_tree.__init__
[4/260] check donnemartin__interactive-coding-challenges.graphs_trees.tree_level_lists.__init__
[5/260] check donnemartin__interactive-coding-challenges.arrays_strings.compress_alt.__init__
[6/260] check donnemartin__interactive-coding-challenges.online_judges.merge_ranges.__init__
[7/260] check donnemartin__interactive-coding-challenges.sorting_searching.insertion_sort.__init__
[8/260] check donnemartin__interactive-coding-challenges.online_judges.utopian_tree.__init__
[9/260] check donnemartin__interactive-coding-challenges.graphs_trees.trie.__init__
[10/260] check donnemartin__interactive-coding-challenges.graphs_trees.bst_successor.__init__
[11/260] check donnemartin__interactive-coding-challenges.online_judges.__init__
[12/260] check donnemartin__interactive-coding-challenges.recursion_dynamic.longest_substring.__init__
[13/260] check check_prime.__init__
[14/260] check donnemartin__interactive-coding-challenges.stacks_queues.queue_from_stacks.__init__
[15/260] check donnemartin__interactive-coding-challenges.stacks_queues.sort_stack.__init__
[16/260] check donnemartin__interactive-coding-challenges.arrays_strings.two_sum.__init__
[17/260] check power_two.__init__
[18/260] check donnemartin__interactive-coding-challenges.arrays_strings.priority_queue.priority_queue
[19/260] check donnemartin__interactive-coding-challenges.linked_lists.linked_list.__init__
[20/260] check donnemartin__interactive-coding-challenges.bit_manipulation.get_next.test_get_next_largest
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/bit_manipulation/get_next/test_get_next_largest.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/imports/donnemartin__interactive-coding-challenges.bit_manipulation.get_next.test_get_next_largest.imports --module-name donnemartin__interactive-coding-challenges.bit_manipulation.get_next.test_get_next_largest -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/bit_manipulation/get_next/test_get_next_largest.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/bit_manipulation/get_next/test_get_next_largest.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/bit_manipulation/get_next/test_get_next_largest.py", line 7, in test_get_next_largest: Name 'Bits' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/bit_manipulation/get_next/test_get_next_largest.py", line 17, in test_get_next_smallest: Name 'Bits' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error
[21/260] check donnemartin__interactive-coding-challenges.online_judges.longest_substr_k_distinct.test_longest_substr
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/online_judges/longest_substr_k_distinct/test_longest_substr.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/imports/donnemartin__interactive-coding-challenges.online_judges.longest_substr_k_distinct.test_longest_substr.imports --module-name donnemartin__interactive-coding-challenges.online_judges.longest_substr_k_distinct.test_longest_substr -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/online_judges/longest_substr_k_distinct/test_longest_substr.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/online_judges/longest_substr_k_distinct/test_longest_substr.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/online_judges/longest_substr_k_distinct/test_longest_substr.py", line 7, in test_longest_substr: Name 'Solution' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error
[22/260] check donnemartin__interactive-coding-challenges.graphs_trees.bst_successor.test_bst_successor
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/graphs_trees/bst_successor/test_bst_successor.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/imports/donnemartin__interactive-coding-challenges.graphs_trees.bst_successor.test_bst_successor.imports --module-name donnemartin__interactive-coding-challenges.graphs_trees.bst_successor.test_bst_successor -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/graphs_trees/bst_successor/test_bst_successor.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/graphs_trees/bst_successor/test_bst_successor.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/graphs_trees/bst_successor/test_bst_successor.py", line 7, in test_bst_successor_empty: Name 'BstSuccessor' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/graphs_trees/bst_successor/test_bst_successor.py", line 12, in test_bst_successor: Name 'Node' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/graphs_trees/bst_successor/test_bst_successor.py", line 14, in test_bst_successor: Name 'Bst' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/graphs_trees/bst_successor/test_bst_successor.py", line 27, in test_bst_successor: Name 'BstSuccessor' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error
[23/260] check donnemartin__interactive-coding-challenges.stacks_queues.set_of_stacks.test_set_of_stacks
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/stacks_queues/set_of_stacks/test_set_of_stacks.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/imports/donnemartin__interactive-coding-challenges.stacks_queues.set_of_stacks.test_set_of_stacks.imports --module-name donnemartin__interactive-coding-challenges.stacks_queues.set_of_stacks.test_set_of_stacks -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/stacks_queues/set_of_stacks/test_set_of_stacks.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/stacks_queues/set_of_stacks/test_set_of_stacks.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/stacks_queues/set_of_stacks/test_set_of_stacks.py", line 8, in test_set_of_stacks: Name 'SetOfStacks' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error
[24/260] check donnemartin__interactive-coding-challenges.bit_manipulation.flip_bit.test_flip_bit
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/bit_manipulation/flip_bit/test_flip_bit.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/imports/donnemartin__interactive-coding-challenges.bit_manipulation.flip_bit.test_flip_bit.imports --module-name donnemartin__interactive-coding-challenges.bit_manipulation.flip_bit.test_flip_bit -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/bit_manipulation/flip_bit/test_flip_bit.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/bit_manipulation/flip_bit/test_flip_bit.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/bit_manipulation/flip_bit/test_flip_bit.py", line 7, in test_flip_bit: Name 'Bits' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error
[25/260] check donnemartin__interactive-coding-challenges.recursion_dynamic.max_profit_k.__init__
[26/260] check donnemartin__interactive-coding-challenges.graphs_trees.utils.results
[27/260] check donnemartin__interactive-coding-challenges.staging.sorting_searching.group_ordered.test_group_ordered
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/staging/sorting_searching/group_ordered/test_group_ordered.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/imports/donnemartin__interactive-coding-challenges.staging.sorting_searching.group_ordered.test_group_ordered.imports --module-name donnemartin__interactive-coding-challenges.staging.sorting_searching.group_ordered.test_group_ordered -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/staging/sorting_searching/group_ordered/test_group_ordered.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/staging/sorting_searching/group_ordered/test_group_ordered.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/staging/sorting_searching/group_ordered/test_group_ordered.py", line 22, in main: Name 'group_ordered' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/staging/sorting_searching/group_ordered/test_group_ordered.py", line 24, in main: Name 'group_ordered_alt' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error
[28/260] check donnemartin__interactive-coding-challenges.online_judges.maximizing_xor.test_maximizing_xor
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/online_judges/maximizing_xor/test_maximizing_xor.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/imports/donnemartin__interactive-coding-challenges.online_judges.maximizing_xor.test_maximizing_xor.imports --module-name donnemartin__interactive-coding-challenges.online_judges.maximizing_xor.test_maximizing_xor -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/online_judges/maximizing_xor/test_maximizing_xor.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/online_judges/maximizing_xor/test_maximizing_xor.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/online_judges/maximizing_xor/test_maximizing_xor.py", line 7, in test_maximizing_xor: Name 'Solution' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error
[29/260] check donnemartin__interactive-coding-challenges.recursion_dynamic.knapsack_unbounded.test_knapsack_unbounded
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/recursion_dynamic/knapsack_unbounded/test_knapsack_unbounded.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/imports/donnemartin__interactive-coding-challenges.recursion_dynamic.knapsack_unbounded.test_knapsack_unbounded.imports --module-name donnemartin__interactive-coding-challenges.recursion_dynamic.knapsack_unbounded.test_knapsack_unbounded -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/recursion_dynamic/knapsack_unbounded/test_knapsack_unbounded.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/recursion_dynamic/knapsack_unbounded/test_knapsack_unbounded.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/recursion_dynamic/knapsack_unbounded/test_knapsack_unbounded.py", line 7, in test_knapsack: Name 'Knapsack' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/recursion_dynamic/knapsack_unbounded/test_knapsack_unbounded.py", line 11, in test_knapsack: Name 'Item' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/recursion_dynamic/knapsack_unbounded/test_knapsack_unbounded.py", line 12, in test_knapsack: Name 'Item' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/recursion_dynamic/knapsack_unbounded/test_knapsack_unbounded.py", line 13, in test_knapsack: Name 'Item' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error
[30/260] check donnemartin__interactive-coding-challenges.linked_lists.add_reverse.__init__
[31/260] check donnemartin__interactive-coding-challenges.graphs_trees.trie.trie
[32/260] check check_prime.test_check_prime
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/check_prime/test_check_prime.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/imports/check_prime.test_check_prime.imports --module-name check_prime.test_check_prime -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/check_prime/test_check_prime.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/math_probability/check_prime/test_check_prime.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/math_probability/check_prime/test_check_prime.py", line 7, in test_check_prime: Name 'Math' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error
[33/260] check donnemartin__interactive-coding-challenges.recursion_dynamic.steps.test_steps
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/recursion_dynamic/steps/test_steps.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/imports/donnemartin__interactive-coding-challenges.recursion_dynamic.steps.test_steps.imports --module-name donnemartin__interactive-coding-challenges.recursion_dynamic.steps.test_steps -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/recursion_dynamic/steps/test_steps.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/recursion_dynamic/steps/test_steps.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/recursion_dynamic/steps/test_steps.py", line 7, in test_steps: Name 'Steps' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error
[34/260] check donnemartin__interactive-coding-challenges.recursion_dynamic.grid_path.test_grid_path
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/recursion_dynamic/grid_path/test_grid_path.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/imports/donnemartin__interactive-coding-challenges.recursion_dynamic.grid_path.test_grid_path.imports --module-name donnemartin__interactive-coding-challenges.recursion_dynamic.grid_path.test_grid_path -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/recursion_dynamic/grid_path/test_grid_path.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/recursion_dynamic/grid_path/test_grid_path.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/recursion_dynamic/grid_path/test_grid_path.py", line 7, in test_grid_path: Name 'Grid' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error
[35/260] check donnemartin__interactive-coding-challenges.staging.arrays_strings.reverse_words.__init__
[36/260] check donnemartin__interactive-coding-challenges.stacks_queues.queue_list.test_queue_list
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/stacks_queues/queue_list/test_queue_list.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/imports/donnemartin__interactive-coding-challenges.stacks_queues.queue_list.test_queue_list.imports --module-name donnemartin__interactive-coding-challenges.stacks_queues.queue_list.test_queue_list -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/stacks_queues/queue_list/test_queue_list.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/stacks_queues/queue_list/test_queue_list.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/stacks_queues/queue_list/test_queue_list.py", line 10, in test_end_to_end: Name 'Queue' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error
[37/260] check donnemartin__interactive-coding-challenges.arrays_strings.permutation.test_permutation_solution
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/arrays_strings/permutation/test_permutation_solution.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/imports/donnemartin__interactive-coding-challenges.arrays_strings.permutation.test_permutation_solution.imports --module-name donnemartin__interactive-coding-challenges.arrays_strings.permutation.test_permutation_solution -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/arrays_strings/permutation/test_permutation_solution.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/arrays_strings/permutation/test_permutation_solution.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/arrays_strings/permutation/test_permutation_solution.py", line 18, in main: Name 'Permutations' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/arrays_strings/permutation/test_permutation_solution.py", line 21, in main: Name 'PermutationsAlt' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error
[38/260] check donnemartin__interactive-coding-challenges.graphs_trees.bst_min.test_bst_min
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/graphs_trees/bst_min/test_bst_min.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/imports/donnemartin__interactive-coding-challenges.graphs_trees.bst_min.test_bst_min.imports --module-name donnemartin__interactive-coding-challenges.graphs_trees.bst_min.test_bst_min -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/graphs_trees/bst_min/test_bst_min.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/graphs_trees/bst_min/test_bst_min.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/graphs_trees/bst_min/test_bst_min.py", line 14, in test_bst_min: Name 'MinBst' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/graphs_trees/bst_min/test_bst_min.py", line 19, in test_bst_min: Name 'MinBst' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error
[39/260] check donnemartin__interactive-coding-challenges.recursion_dynamic.magic_index.test_find_magic_index
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/recursion_dynamic/magic_index/test_find_magic_index.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/imports/donnemartin__interactive-coding-challenges.recursion_dynamic.magic_index.test_find_magic_index.imports --module-name donnemartin__interactive-coding-challenges.recursion_dynamic.magic_index.test_find_magic_index -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/recursion_dynamic/magic_index/test_find_magic_index.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/recursion_dynamic/magic_index/test_find_magic_index.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/recursion_dynamic/magic_index/test_find_magic_index.py", line 7, in test_find_magic_index: Name 'MagicIndex' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error
[40/260] check donnemartin__interactive-coding-challenges.graphs_trees.check_balance.test_check_balance
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/graphs_trees/check_balance/test_check_balance.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/imports/donnemartin__interactive-coding-challenges.graphs_trees.check_balance.test_check_balance.imports --module-name donnemartin__interactive-coding-challenges.graphs_trees.check_balance.test_check_balance -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/graphs_trees/check_balance/test_check_balance.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/graphs_trees/check_balance/test_check_balance.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/graphs_trees/check_balance/test_check_balance.py", line 7, in test_check_balance_empty: Name 'BstBalance' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/graphs_trees/check_balance/test_check_balance.py", line 11, in test_check_balance: Name 'BstBalance' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/graphs_trees/check_balance/test_check_balance.py", line 11, in test_check_balance: Name 'Node' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/graphs_trees/check_balance/test_check_balance.py", line 20, in test_check_balance: Name 'BstBalance' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/graphs_trees/check_balance/test_check_balance.py", line 20, in test_check_balance: Name 'Node' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/graphs_trees/check_balance/test_check_balance.py", line 27, in test_check_balance: Name 'BstBalance' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/graphs_trees/check_balance/test_check_balance.py", line 27, in test_check_balance: Name 'Node' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error
[41/260] check donnemartin__interactive-coding-challenges.online_judges.sentence_screen_fit.test_count_sentence_fit
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/online_judges/sentence_screen_fit/test_count_sentence_fit.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/imports/donnemartin__interactive-coding-challenges.online_judges.sentence_screen_fit.test_count_sentence_fit.imports --module-name donnemartin__interactive-coding-challenges.online_judges.sentence_screen_fit.test_count_sentence_fit -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/online_judges/sentence_screen_fit/test_count_sentence_fit.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/online_judges/sentence_screen_fit/test_count_sentence_fit.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/online_judges/sentence_screen_fit/test_count_sentence_fit.py", line 7, in test_count_sentence_fit: Name 'Solution' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error
[42/260] check donnemartin__interactive-coding-challenges.linked_lists.add_reverse.test_add_reverse
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/linked_lists/add_reverse/test_add_reverse.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/imports/donnemartin__interactive-coding-challenges.linked_lists.add_reverse.test_add_reverse.imports --module-name donnemartin__interactive-coding-challenges.linked_lists.add_reverse.test_add_reverse -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/linked_lists/add_reverse/test_add_reverse.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/linked_lists/add_reverse/test_add_reverse.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/linked_lists/add_reverse/test_add_reverse.py", line 8, in test_add_reverse: Name 'MyLinkedList' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/linked_lists/add_reverse/test_add_reverse.py", line 9, in test_add_reverse: Name 'MyLinkedList' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/linked_lists/add_reverse/test_add_reverse.py", line 9, in test_add_reverse: Name 'Node' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/linked_lists/add_reverse/test_add_reverse.py", line 10, in test_add_reverse: Name 'MyLinkedList' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/linked_lists/add_reverse/test_add_reverse.py", line 10, in test_add_reverse: Name 'Node' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/linked_lists/add_reverse/test_add_reverse.py", line 16, in test_add_reverse: Name 'MyLinkedList' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/linked_lists/add_reverse/test_add_reverse.py", line 16, in test_add_reverse: Name 'Node' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/linked_lists/add_reverse/test_add_reverse.py", line 18, in test_add_reverse: Name 'MyLinkedList' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/linked_lists/add_reverse/test_add_reverse.py", line 18, in test_add_reverse: Name 'Node' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/linked_lists/add_reverse/test_add_reverse.py", line 21, in test_add_reverse: Name 'MyLinkedList' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/linked_lists/add_reverse/test_add_reverse.py", line 28, in test_add_reverse: Name 'Node' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/linked_lists/add_reverse/test_add_reverse.py", line 29, in test_add_reverse: Name 'MyLinkedList' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/linked_lists/add_reverse/test_add_reverse.py", line 32, in test_add_reverse: Name 'Node' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/linked_lists/add_reverse/test_add_reverse.py", line 33, in test_add_reverse: Name 'MyLinkedList' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/linked_lists/add_reverse/test_add_reverse.py", line 36, in test_add_reverse: Name 'MyLinkedList' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error
[43/260] check donnemartin__interactive-coding-challenges.arrays_strings.str_diff.test_str_diff
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/arrays_strings/str_diff/test_str_diff.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/imports/donnemartin__interactive-coding-challenges.arrays_strings.str_diff.test_str_diff.imports --module-name donnemartin__interactive-coding-challenges.arrays_strings.str_diff.test_str_diff -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/donnemartin__interactive-coding-challenges/pyi/donnemartin__interactive-coding-challenges/arrays_strings/str_diff/test_str_diff.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/arrays_strings/str_diff/test_str_diff.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/donnemartin__interactive-coding-challenges/arrays_strings/str_diff/test_str_diff.py", line 7, in test_find_diff: Name 'Solution' is not defined [name-error]

For more details, see https://google.github.io/pytype/errors.html#name-error
ninja: build stopped: subcommand failed.
Leaving directory 'output/donnemartin__interactive-coding-challenges'
