Computing dependencies
Analyzing 1 sources with 0 local dependencies
ninja: Entering directory `output/josephmisiti__awesome-machine-learning'
[1/1] check pull_R_packages
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/josephmisiti__awesome-machine-learning/pyi/pull_R_packages.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/josephmisiti__awesome-machine-learning/imports/pull_R_packages.imports --module-name pull_R_packages -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/josephmisiti__awesome-machine-learning/pyi/pull_R_packages.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/josephmisiti__awesome-machine-learning/scripts/pull_R_packages.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/josephmisiti__awesome-machine-learning/scripts/pull_R_packages.py", line 9, in <module>: Can't find module 'pyquery'. [import-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/josephmisiti__awesome-machine-learning/scripts/pull_R_packages.py", line 16, in <lambda>: No attribute 'urlopen' on module 'urllib' [module-attr]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/josephmisiti__awesome-machine-learning/scripts/pull_R_packages.py", line 25, in <lambda>: No attribute 'urlopen' on module 'urllib' [module-attr]

For more details, see https://google.github.io/pytype/errors.html
ninja: build stopped: subcommand failed.
Leaving directory 'output/josephmisiti__awesome-machine-learning'
