Computing dependencies
Analyzing 6 sources with 0 local dependencies
ninja: Entering directory `output/beurtschipper__Depix'
[1/6] check depixlib.Rectangle
[2/6] check depixlib.__init__
[3/6] check depixlib.LoadedImage
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/beurtschipper__Depix/pyi/depixlib/LoadedImage.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/beurtschipper__Depix/imports/depixlib.LoadedImage.imports --module-name depixlib.LoadedImage -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/beurtschipper__Depix/pyi/depixlib/LoadedImage.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/beurtschipper__Depix/depixlib/LoadedImage.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/beurtschipper__Depix/depixlib/LoadedImage.py", line 17, in getCopyOfLoadedPILImage: No attribute 'copy' on bool [attribute-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/beurtschipper__Depix/depixlib/LoadedImage.py", line 35, in loadImageData: No attribute 'getdata' on bool [attribute-error]
Called from (traceback):
  line 13, in __init__

For more details, see https://google.github.io/pytype/errors.html#attribute-error
[4/6] check depixlib.functions
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/beurtschipper__Depix/pyi/depixlib/functions.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/beurtschipper__Depix/imports/depixlib.functions.imports --module-name depixlib.functions -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/beurtschipper__Depix/pyi/depixlib/functions.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/beurtschipper__Depix/depixlib/functions.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/beurtschipper__Depix/depixlib/functions.py", line 299, in writeAverageMatchToImage: Function PIL.Image.new was called with the wrong arguments [wrong-arg-types]
         Expected: (mode, size, color: Union[Tuple[Union[float, int], ...], float, int] = ...)
  Actually passed: (mode, size, color: str)

For more details, see https://google.github.io/pytype/errors.html#wrong-arg-types
ninja: build stopped: subcommand failed.
Leaving directory 'output/beurtschipper__Depix'
