Computing dependencies
Analyzing 35 sources with 0 local dependencies
ninja: Entering directory `output/psf__requests'
[1/35] check tests.testserver.__init__
[2/35] check requests.__version__
[3/35] check requests.hooks
[4/35] check requests.certs
[5/35] check tests.utils
[6/35] check flask_theme_support
[7/35] check tests.__init__
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/psf__requests/pyi/tests/__init__.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/psf__requests/imports/tests.__init__.imports --module-name tests.__init__ -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/psf__requests/pyi/tests/__init__.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/tests/__init__.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/tests/__init__.py", line 7, in <module>: Can't find module 'urllib3'. [import-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/tests/__init__.py", line 8, in <module>: Can't find module 'urllib3.exceptions'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[8/35] check requests.packages
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/psf__requests/pyi/requests/packages.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/psf__requests/imports/requests.packages.imports --module-name requests.packages -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/psf__requests/pyi/requests/packages.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/requests/packages.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/requests/packages.py", line 6, in <module>: Can't find module 'charset_normalizer'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[9/35] check tests.testserver.server
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/psf__requests/pyi/tests/testserver/server.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/psf__requests/imports/tests.testserver.server.imports --module-name tests.testserver.server -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/psf__requests/pyi/tests/testserver/server.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/tests/testserver/server.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/tests/testserver/server.py", line 88, in _close_server_sock_ignore_errors: No attribute 'server_sock' on Server [attribute-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/tests/testserver/server.py", line 105, in _accept_connection: No attribute 'server_sock' on Server [attribute-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/tests/testserver/server.py", line 109, in _accept_connection: No attribute 'server_sock' on Server [attribute-error]

For more details, see https://google.github.io/pytype/errors.html#attribute-error
[10/35] check setup
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/psf__requests/pyi/setup.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/psf__requests/imports/setup.imports --module-name setup -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/psf__requests/pyi/setup.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/setup.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/setup.py", line 30, in run_tests: Can't find module 'pytest'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[11/35] check requests.compat
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/psf__requests/pyi/requests/compat.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/psf__requests/imports/requests.compat.imports --module-name requests.compat -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/psf__requests/pyi/requests/compat.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/requests/compat.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/requests/compat.py", line 14, in <module>: Can't find module 'charset_normalizer'. [import-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/requests/compat.py", line 64, in <module>: Can't find module 'urllib.request.proxy_bypass_environment'. [import-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/requests/compat.py", line 64, in <module>: Can't find module 'urllib.request.getproxies_environment'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[12/35] check tests.test_hooks
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/psf__requests/pyi/tests/test_hooks.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/psf__requests/imports/tests.test_hooks.imports --module-name tests.test_hooks -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/psf__requests/pyi/tests/test_hooks.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/tests/test_hooks.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/tests/test_hooks.py", line 3, in <module>: Can't find module 'pytest'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[13/35] check requests.help
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/psf__requests/pyi/requests/help.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/psf__requests/imports/requests.help.imports --module-name requests.help -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/psf__requests/pyi/requests/help.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/requests/help.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/requests/help.py", line 9, in <module>: Can't find module 'idna'. [import-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/requests/help.py", line 10, in <module>: Can't find module 'urllib3'. [import-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/requests/help.py", line 15, in <module>: Can't find module 'charset_normalizer'. [import-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/requests/help.py", line 25, in <module>: Can't find module 'urllib3.contrib'. [import-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/requests/help.py", line 51, in _implementation: No attribute 'pypy_version_info' on module 'sys' [module-attr]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/requests/help.py", line 52, in _implementation: No attribute 'pypy_version_info' on module 'sys' [module-attr]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/requests/help.py", line 53, in _implementation: No attribute 'pypy_version_info' on module 'sys' [module-attr]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/requests/help.py", line 54, in _implementation: No attribute 'pypy_version_info' on module 'sys' [module-attr]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/requests/help.py", line 56, in _implementation: No attribute 'pypy_version_info' on module 'sys' [module-attr]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/psf__requests/requests/help.py", line 96, in info: No attribute '__version__' on module 'OpenSSL' [module-attr]

For more details, see https://google.github.io/pytype/errors.html
ninja: build stopped: subcommand failed.
Leaving directory 'output/psf__requests'
