Computing dependencies
Analyzing 411 sources with 4 local dependencies
ninja: Entering directory `output/nvbn__thefuck'
[1/425] check thefuck.rules.dry
[2/425] check thefuck.specific.__init__
[3/425] check tests.__init__
[4/425] check thefuck.rules.cd_cs
[5/425] check tests.functional.plots
[6/425] check thefuck.rules.quotation_marks
[7/425] check thefuck.rules.__init__
[8/425] check thefuck.rules.django_south_merge
[9/425] check thefuck.rules.sl_ls
[10/425] check thefuck.rules.cd_parent
[11/425] check thefuck.rules.remove_trailing_cedilla
[12/425] check thefuck.rules.test.py
[13/425] check thefuck.exceptions
[14/425] check thefuck.rules.man_no_space
[15/425] check thefuck.rules.django_south_ghost
[16/425] check tests.shells.__init__
[17/425] check thefuck.rules.sudo
[18/425] check tests.functional.__init__
[19/425] check thefuck.rules.unsudo
[20/425] check thefuck.const
[21/425] check thefuck.__init__
[22/425] check thefuck.rules.cargo
[23/425] check tests.test_readme
[24/425] check tests.specific.__init__
[25/425] check tests.entrypoints.__init__
[26/425] check thefuck.entrypoints.__init__
[27/425] check tests.rules.__init__
[28/425] check thefuck.rules.remove_shell_prompt_literal
[29/425] check tests.functional.test_tcsh
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/pyi/tests/functional/test_tcsh.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/imports/tests.functional.test_tcsh.imports --module-name tests.functional.test_tcsh -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/pyi/tests/functional/test_tcsh.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/nvbn__thefuck/tests/functional/test_tcsh.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/nvbn__thefuck/tests/functional/test_tcsh.py", line 1, in <module>: Can't find module 'pytest'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[30/425] check tests.functional.test_zsh
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/pyi/tests/functional/test_zsh.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/imports/tests.functional.test_zsh.imports --module-name tests.functional.test_zsh -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/pyi/tests/functional/test_zsh.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/nvbn__thefuck/tests/functional/test_zsh.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/nvbn__thefuck/tests/functional/test_zsh.py", line 1, in <module>: Can't find module 'pytest'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[31/425] check tests.functional.test_bash
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/pyi/tests/functional/test_bash.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/imports/tests.functional.test_bash.imports --module-name tests.functional.test_bash -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/pyi/tests/functional/test_bash.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/nvbn__thefuck/tests/functional/test_bash.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/nvbn__thefuck/tests/functional/test_bash.py", line 1, in <module>: Can't find module 'pytest'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[32/425] check tests.functional.test_fish
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/pyi/tests/functional/test_fish.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/imports/tests.functional.test_fish.imports --module-name tests.functional.test_fish -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/pyi/tests/functional/test_fish.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/nvbn__thefuck/tests/functional/test_fish.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/nvbn__thefuck/tests/functional/test_fish.py", line 1, in <module>: Can't find module 'pytest'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[33/425] check tests.shells.conftest
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/pyi/tests/shells/conftest.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/imports/tests.shells.conftest.imports --module-name tests.shells.conftest -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/pyi/tests/shells/conftest.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/nvbn__thefuck/tests/shells/conftest.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/nvbn__thefuck/tests/shells/conftest.py", line 1, in <module>: Can't find module 'pytest'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[34/425] check release
[35/425] check fastentrypoints
[36/425] check thefuck.system.win32
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/pyi/thefuck/system/win32.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/imports/thefuck.system.win32.imports --module-name thefuck.system.win32 -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/pyi/thefuck/system/win32.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/nvbn__thefuck/thefuck/system/win32.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/nvbn__thefuck/thefuck/system/win32.py", line 3, in <module>: Can't find module 'win_unicode_console'. [import-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/nvbn__thefuck/thefuck/system/win32.py", line 14, in get_key: No attribute 'getwch' on module 'msvcrt' [module-attr]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/nvbn__thefuck/thefuck/system/win32.py", line 16, in get_key: No attribute 'getwch' on module 'msvcrt' [module-attr]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/nvbn__thefuck/thefuck/system/win32.py", line 35, in <module>: Can't find module 'pathlib2'. [import-error]

For more details, see https://google.github.io/pytype/errors.html
[37/425] check thefuck.system.unix
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/pyi/thefuck/system/unix.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/imports/thefuck.system.unix.imports --module-name thefuck.system.unix -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/pyi/thefuck/system/unix.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/nvbn__thefuck/thefuck/system/unix.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/nvbn__thefuck/thefuck/system/unix.py", line 49, in <module>: Can't find module 'pathlib2'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[38/425] check thefuck.specific.sudo
[39/425] check tests.test_conf
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/pyi/tests/test_conf.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/imports/tests.test_conf.imports --module-name tests.test_conf -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/nvbn__thefuck/pyi/tests/test_conf.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/nvbn__thefuck/tests/test_conf.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/nvbn__thefuck/tests/test_conf.py", line 1, in <module>: Can't find module 'pytest'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
ninja: build stopped: subcommand failed.
Leaving directory 'output/nvbn__thefuck'
