Computing dependencies
Analyzing 8 sources with 0 local dependencies
ninja: Entering directory `output/satwikkansal__wtfpython'
[1/8] check mixed_tabs_and_spaces
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/satwikkansal__wtfpython/pyi/mixed_tabs_and_spaces.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/satwikkansal__wtfpython/imports/mixed_tabs_and_spaces.imports --module-name mixed_tabs_and_spaces -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/satwikkansal__wtfpython/pyi/mixed_tabs_and_spaces.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/satwikkansal__wtfpython/mixed_tabs_and_spaces.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/satwikkansal__wtfpython/mixed_tabs_and_spaces.py", line 5: inconsistent use of tabs and spaces in indentation [python-compiler-error]

For more details, see https://google.github.io/pytype/errors.html#python-compiler-error
[2/8] check wtf_python.__init__
[3/8] check parse_readme
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/satwikkansal__wtfpython/pyi/parse_readme.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/satwikkansal__wtfpython/imports/parse_readme.imports --module-name parse_readme -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/satwikkansal__wtfpython/pyi/parse_readme.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/satwikkansal__wtfpython/irrelevant/obsolete/parse_readme.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/satwikkansal__wtfpython/irrelevant/obsolete/parse_readme.py", line 14, in <module>: Name 'raw_input' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/satwikkansal__wtfpython/irrelevant/obsolete/parse_readme.py", line 24, in <module>: No attribute 'next' on listiterator[str] [attribute-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/satwikkansal__wtfpython/irrelevant/obsolete/parse_readme.py", line 32, in <module>: No attribute 'next' on listiterator[str] [attribute-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/satwikkansal__wtfpython/irrelevant/obsolete/parse_readme.py", line 37, in <module>: No attribute 'next' on listiterator[str] [attribute-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/satwikkansal__wtfpython/irrelevant/obsolete/parse_readme.py", line 44, in <module>: No attribute 'next' on listiterator[str] [attribute-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/satwikkansal__wtfpython/irrelevant/obsolete/parse_readme.py", line 56, in <module>: No attribute 'next' on listiterator[str] [attribute-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/satwikkansal__wtfpython/irrelevant/obsolete/parse_readme.py", line 60, in <module>: Name 'title' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/satwikkansal__wtfpython/irrelevant/obsolete/parse_readme.py", line 61, in <module>: Name 'description' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/satwikkansal__wtfpython/irrelevant/obsolete/parse_readme.py", line 62, in <module>: Name 'explanation' is not defined [name-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/satwikkansal__wtfpython/irrelevant/obsolete/parse_readme.py", line 79, in <module>: No attribute 'next' on listiterator[str] [attribute-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/satwikkansal__wtfpython/irrelevant/obsolete/parse_readme.py", line 80, in <module>: No attribute 'next' on listiterator[str] [attribute-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/satwikkansal__wtfpython/irrelevant/obsolete/parse_readme.py", line 87, in <module>: No attribute 'next' on listiterator[str] [attribute-error]

For more details, see https://google.github.io/pytype/errors.html
[4/8] check setup
[5/8] check insert_ids
[6/8] check wtf_python.main
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/satwikkansal__wtfpython/pyi/wtf_python/main.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/satwikkansal__wtfpython/imports/wtf_python.main.imports --module-name wtf_python.main -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/satwikkansal__wtfpython/pyi/wtf_python/main.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/satwikkansal__wtfpython/wtfpython-pypi/wtf_python/main.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/satwikkansal__wtfpython/wtfpython-pypi/wtf_python/main.py", line 7, in <module>: Can't find module 'urllib.urlretrieve'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[7/8] check notebook_generator
ERROR:pytype.analyze No visible options for read_only
[8/8] check generate_contributions
ninja: build stopped: subcommand failed.
Leaving directory 'output/satwikkansal__wtfpython'
