Computing dependencies
Analyzing 29 sources with 0 local dependencies
ninja: Entering directory `output/deezer__spleeter'
[1/33] check spleeter.resources.__init__
[2/33] check tests.__init__
[3/33] check spleeter.__init__
[4/33] check spleeter.utils.__init__
[5/33] check spleeter.types
[6/33] check spleeter.model.functions.__init__
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/deezer__spleeter/pyi/spleeter/model/functions/__init__.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/deezer__spleeter/imports/spleeter.model.functions.__init__.imports --module-name spleeter.model.functions.__init__ -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/deezer__spleeter/pyi/spleeter/model/functions/__init__.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/deezer__spleeter/spleeter/model/functions/__init__.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/deezer__spleeter/spleeter/model/functions/__init__.py", line 10, in <module>: Can't find module 'tensorflow'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[7/33] check spleeter.utils.tensor
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/deezer__spleeter/pyi/spleeter/utils/tensor.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/deezer__spleeter/imports/spleeter.utils.tensor.imports --module-name spleeter.utils.tensor -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/deezer__spleeter/pyi/spleeter/utils/tensor.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/deezer__spleeter/spleeter/utils/tensor.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/deezer__spleeter/spleeter/utils/tensor.py", line 12, in <module>: Can't find module 'tensorflow'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[8/33] check spleeter.audio.__init__
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/deezer__spleeter/pyi/spleeter/audio/__init__.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/deezer__spleeter/imports/spleeter.audio.__init__.imports --module-name spleeter.audio.__init__ -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/deezer__spleeter/pyi/spleeter/audio/__init__.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/deezer__spleeter/spleeter/audio/__init__.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/deezer__spleeter/spleeter/audio/__init__.py", line 44, in resolve: Can't find module 'tensorflow'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[9/33] check spleeter.audio.spectrogram
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/deezer__spleeter/pyi/spleeter/audio/spectrogram.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/deezer__spleeter/imports/spleeter.audio.spectrogram.imports --module-name spleeter.audio.spectrogram -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/deezer__spleeter/pyi/spleeter/audio/spectrogram.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/deezer__spleeter/spleeter/audio/spectrogram.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/deezer__spleeter/spleeter/audio/spectrogram.py", line 9, in <module>: Can't find module 'tensorflow'. [import-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/deezer__spleeter/spleeter/audio/spectrogram.py", line 10, in <module>: Can't find module 'tensorflow.signal'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[10/33] check spleeter.utils.logging
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/deezer__spleeter/pyi/spleeter/utils/logging.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/deezer__spleeter/imports/spleeter.utils.logging.imports --module-name spleeter.utils.logging -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/deezer__spleeter/pyi/spleeter/utils/logging.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/deezer__spleeter/spleeter/utils/logging.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/deezer__spleeter/spleeter/utils/logging.py", line 12, in <module>: Can't find module 'typer'. [import-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/deezer__spleeter/spleeter/utils/logging.py", line 46, in configure_logger: Can't find module 'tensorflow'. [import-error]
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/deezer__spleeter/spleeter/utils/logging.py", line 47, in configure_logger: Can't find module 'tensorflow.compat.v1'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
[11/33] check spleeter.utils.configuration
FAILED: /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/deezer__spleeter/pyi/spleeter/utils/configuration.pyi 
/mnt/c/Users/nitram/PycharmProjects/pytype_runner/env/bin/python3 -m pytype.single --imports_info /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/deezer__spleeter/imports/spleeter.utils.configuration.imports --module-name spleeter.utils.configuration -V 3.8 -o /mnt/c/Users/nitram/PycharmProjects/pytype_runner/output/deezer__spleeter/pyi/spleeter/utils/configuration.pyi --analyze-annotated --nofail --quick /mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/deezer__spleeter/spleeter/utils/configuration.py
File "/mnt/c/Users/nitram/PycharmProjects/git_cloner/all_repos/deezer__spleeter/spleeter/utils/configuration.py", line 15, in <module>: Can't find module 'importlib_resources'. [import-error]

For more details, see https://google.github.io/pytype/errors.html#import-error
ninja: build stopped: subcommand failed.
Leaving directory 'output/deezer__spleeter'
